version: '3.9'
services:
  web:
    container_name: software-testing.uu.se
    image: uu/software-testing
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src

networks:
  default:
    name: uu-server
    external: true
